### ISSUE TITLE
Viro React support?

### ISSUE THREAD

**Issue by robertjuh** [expo/expo-three#37]
I was trying to use expo-three within Viro React but i didn't seem to get it to work. It seems like it would be perfect if this was possible, given that Viro React has Augmented Reality + Virtual reality and both IOS and Android. 

For a project i need to integrate a part of an existing THREEjs website into my native react AR app. 

Any knowledge about this matter? I can provide detailed logs and explanations if required.

**Comment by EvanBacon** [comment]
**expo-three** uses the most advanced version of an OpenGL-ES to WebGL bridge ([This is an out of date spin-off](https://github.com/react-community/react-native-webgl )). 
From what I understand, Viro has their own native rendering library which wouldn't have much compatibility with this API. 
Basically EXGL allows you to write WebGL, and then bridge it to native OpenGL-ES which means that support for web libraries like three.js, pixi.j, phaser.js, processing.js work automatically. 
With Viro everything would have to be rewritten from scratch and wouldn't have the support that we get for popular libraries like pixi.js and three.js. 
When put in this context I hope you can see why it would be much easier to just add ARCore support and advance ARKit a little more 😂 

This isn't a very scientific opinion by the way, maybe there is something I'm missing. 🤷‍♀️
It's also worth noting that Expo currently bundles all of it's libraries together, and things like ARKit can be tricky because apple will reject your app if you include support and don't use it.

**Comment by robertjuh** [comment]
Hey Evan, thanks for the explanation!

I have experimented with the out of date spin-off and managed to get a 'canvas' with a 1px red border on one side (so something is probably wrong with the element but i have no clue what, as i just followed the little documentation that was available). Managed to import the THREE library but haven't managed to render a 3D object yet.

I just didnt really follow: 
> When put in this context I hope you can see why it would be much easier to just add ARCore support and advance ARKit a little more 

Viro already has ARCore and ARKit support.

**Comment by robertjuh** [comment]
Ah! as you mentioned in the other thread: ARCore and ARKit support for expo.

**Comment by EvanBacon** [comment]
Yeah so expo's version of GL has support for webgl 2.0 and OpenGL-ES 3.0. This means it's way faster. Expo is also working on a canvas implementation internally. I may have partially leaked the wip version of this in the library `@expo/browser-polyfill` to get expo-phaser working properly. 
Viro has ARCore and ARKit but it's attached to their own system, this system isn't compatible with any other framework like three.js, babylon.js, pixi.js, phaser.js. It would be easier to add arkit and arcore to expo than it would be for viro to add the same features provided by every gl web framework.

**Comment by robertjuh** [comment]
Alright, thanks for the explanation!
